const proxyServer = require('../proxyServer')

function ProxyPackPlugin({
  browser,
  domain,
  externalMappings,
  localMappings,
  webpackMappings,
}) {
  proxyServer.init({
    browser,
    domain,
    externalMappings,
    localMappings,
    webpackMappings,
  })
}

ProxyPackPlugin.prototype.apply = function(compiler) {
  compiler.plugin(
    'emit',
    function(compilation, callback) {
      const files = {}
      // Explore each chunk (build output):
      compilation.chunks.forEach(function(chunk) {
        // Explore each asset filename generated by the chunk:
        chunk.files.forEach(function(filename) {
          // Get the asset source for each file generated by the chunk:
          files[filename] = compilation.assets[filename].source()
        })
      })
      proxyServer && proxyServer.updateWebpackAssets(files)
      callback()
    }.bind(this),
  )
}

module.exports = ProxyPackPlugin
